name: yd
version: '0.1' 
summary: yd
description: |
  This is youdao snap dictionary

grade: stable
confinement: strict

apps:
  yd:
    command: yd
    plugs:
      - network
      - home
      - opengl
      - pulseaudio

parts:
  app:
    source: ./src
    plugin: python2

  dict:
    plugin: dump
    source: ./dicts
    organize:
      '*': dicts/
